mavlink/MAVSDK-Proto

core/core.proto, discovery/discovery.proto
This is trying to define the client interface for multi-devices (feel free to suggest other ways if you find this unintuitive!).
* A client fetches the list of known devices through a "discovery" module.
* If a client doesn't know any discovery module, it can start one on its own.
* The discovery module listens for both dronecore instances and mavlink instances (for the latter, the client might want to start a dronecore instance).
* For each discovered device, the module gives a UUID and an address, and says if it is a dronecore instance or not (in which case it is a mavlink instance).
* When a client knows the address of the dronecore instance it wants to use, it can lists the corresponding plugins and get, for each of them, the address of the corresponding grpc server.
In the first …
=> define discovery protocol

mission/mission.proto
I missed it when creating the file, but it is actually there in the `mission.h` interface.
=> download request should have a mission_result

camera/camera.proto
* Add missing SubscribeCameraStatus
* Update the settings interface with SubscribeCurrentSetting, SubscribePossibleSettings, SetSetting.
The idea is that when you SubscribePossibleSettings, you receive all the settings and the options to which you can set them, together with a description (of the setting and its options). When you SubscribeCurrentSettings and SetSettings, it is assumed you know the settings and options by id already.
Fixes #14.
=> Add camera status and settings

action/action.proto, camera/camera.proto, core/core.proto, discovery/discovery.proto, gimbal/gimbal.proto, mission/mission.proto, telemetry/telemetry.proto
We're transitioning from DroneCore to the Dronecode SDK, and this is part of the rename.
=> Rename droncore to dronecode_sdk

pb_plugins/dcsdkgen/autogen.py, pb_plugins/dcsdkgen/methods.py, pb_plugins/dcsdkgen/struct.py, pb_plugins/dcsdkgen/utils.py, pb_plugins/templates/swift/method_observable.j2, pb_plugins/templates/swift/method_single.j2, protos/mission/mission.proto
Parsing the return type of methods (single, observable) and passing it to the templates.
For generation purpose, `*Response` messages can now have a `Result` type (e.g. `MissionResult`, `ActionResult`, ...) and maximum one parameter (which may be a tuple).
=> Parse return type of methods

pb_plugins/dcsdkgen/methods.py, pb_plugins/dcsdkgen/utils.py, pb_plugins/templates/swift/file.j2, pb_plugins/templates/swift/method_observable.j2, pb_plugins/templates/swift/method_single.j2
Check if the return type is a primitive type or not. If not, the message/enum needs to be translated.
@xvzf
=> Handle complex return types

protos/calibration/calibration.proto
I needed to add "optional" `ProgressData` here, because sometimes we may receive a progress (when result is `IN_PROGRESS`) and sometimes we receive a status text (e.g. when result is `INSTRUCTION`).
Hopefully that works, but I'll see in the actual implementation.
=> Add calibration proto

pb_plugins/dcsdkgen/methods.py, pb_plugins/dcsdkgen/struct.py, pb_plugins/dcsdkgen/type_info.py, pb_plugins/dcsdkgen/utils.py
This is a proposition for #47. It looks for a file called `type_conversions` in the templates folder, and if existing, uses it for converting c++ types into whatever is defined in the file.
The file is expected to be a json object where keys are the c++ types and values are their conversions.
Fixes #47
=> Add TypeInfo to manage types and their conversions

pb_plugins/dcsdkgen/struct.py, pb_plugins/dcsdkgen/utils.py
I realized that this one is actually needed: `Subscribe*` comes from the proto file, and we need to remove the prefix before we pass the name to the templates.
=> fix missing remove_subscribe function

pb_plugins/dcsdkgen/name_parser.py, pb_plugins/test/__init__.py, pb_plugins/test/test_name_parser.py
Can be started with 'python -m unittest test.test_name_parser -v' from pb_plugins.
First time I write unit tests in python, so @xvzf let me know if that's not the right way :-).
=> Add unit tests for NameParser

protos/telemetry/telemetry.proto
It is impossible to know if RCGPS is one, two, ... five words without having a convention. So we should keep UpperCamelCase, so that RcGps is easy to parse.
=> Names should follow the UpperCamelCase convention, for later parsing

protos/mission/mission.proto
Because depending of the language, a plugin becomes a class (`<Plugin>`), and a message becomes a class as well (`<Plugin>`), resulting in a conflict.
=> A message name cannot be identical to the plugin name

pb_plugins/dcsdkgen/type_info.py, pb_plugins/dcsdkgen/utils.py, pb_plugins/test/test_type_info.py
The conversion dict file now can have a `repeated` entry that defines the `prefix` and `suffix` for a repeated type.
For instance, the default is:
{ "repeated", { "prefix": "std::vector<", "suffix": ">" } }
Meaning that a `repeated double` will become `std::vector<double>`.
=> add support for repeated types in TypeInfo

protos/calibration/calibration.proto
That's just our naming convention.
=> calibration: streams should be called Subscribe*

pb_plugins/dcsdkgen/autogen.py, pb_plugins/dcsdkgen/enum.py, pb_plugins/dcsdkgen/struct.py, pb_plugins/dcsdkgen/type_info.py, pb_plugins/test/test_type_info.py
* Add recursive support for nested structs: a struct can contain structs and enums now
* An enum must know in which struct it is defined, because its values are defined in the namespace of the parent (hence the need for this `parent_struct` in `Enum`)
* Need to expose the "inner name" of a repeated type. Say for `std::vector<int>`, templates sometimes need to access `int` only.
@xvzf: FYI. I'm merging because that's already a big improvement, but I'd be happy to have your review and improve that later.
=> Support nested structs

pb_plugins/dcsdkgen/name_parser.py, pb_plugins/test/test_name_parser.py
It was assuming upper camel case before, but it actually happens that the input arrives as lower_snake_case.
Also, uppercase should keep underscores (e.g. `TakePhoto` should become `TAKE_PHOTO` and not `TAKEPHOTO`, which doesn't really make sense).
Finally, lowercase is apparently superfluous.
=> pb_plugins: improve name_parser inputs handling

pb_plugins/dcsdkgen/autogen.py, pb_plugins/dcsdkgen/autogen_file.py, pb_plugins/dcsdkgen/methods.py, pb_plugins/dcsdkgen/utils.py
There is a need to know if a file or a method contains a result or not. In Python, for instance, a method may raise an error if the result is not SUCCESS. If there is no result, it means that the method cannot fail, in which case it should not do anything.
=> pb_plugins: add has_result to methods and file

pb_plugins/dcsdkgen/autogen_file.py, pb_plugins/dcsdkgen/enum.py, pb_plugins/dcsdkgen/methods.py, pb_plugins/dcsdkgen/name_parser.py, pb_plugins/dcsdkgen/struct.py, pb_plugins/dcsdkgen/utils.py, pb_plugins/test/test_name_parser.py
Some languages find that "Url" is much more difficult to understand than "URL", and that it is worth breaking the cONsiStENCy of CamelCase by keeping initialisms capitalized. And because it is not so easy to have a list of such initialisms, there are only 4 of them in swift-protobuf (nice, isn't it? :sweat_smile:). 
We have to deal with it, because otherwise our generated code doesn't compile with code generated by swift-protobuf. Therefore, I added a list of initialisms in `NameParser`, so that we can break our consistency, too, for those languages.
Notes:
* `NameParser` takes a list of initialisms without a default, because I want to force the use of `NameParserFactory`. 
* The way I treat the initialisms below (with long `map` lines) is not super elegant, but I did not find a better …
=> pb_plugins: add support for initialisms

pb_plugins/dcsdkgen/methods.py
Previously, we were first checking if a method was a `Call` by checking if it has no return value. However, we could have a stream of `void` elements. This PR makes it such that we first check if a method is a `stream`.
Also, because a stream can have no return value, we need to set it to `None`, so that the template can deal with it.
I wonder if it makes sense to support streams of `void`, but we have one already, so it has to be supported. Maybe later, `discover` and `timeout` (in Core) should be merged, and then we could decide to not support streams of `void`...
=> Fix method type detection

protos/core/core.proto
That was an old suggestion from @byuarus, which I believe makes sense. In practice, we mostly use both calls together.
Note that in the middle term this will change the C++ API as well (when it is auto-generated). But I believe it makes sense there as well.
=> core: merge 'discover' and 'timeout' into a single 'connection_state'

pb_plugins/dcsdkgen/autogen.py, pb_plugins/dcsdkgen/name_parser.py, pb_plugins/dcsdkgen/type_info.py, pb_plugins/dcsdkgen/utils.py, pb_plugins/test/test_name_parser.py, pb_plugins/test/test_type_info.py
Our protoc plugin now takes `template_path` from the protoc options. The goal is to not have to use the `TEMPLATE_PATH` environment variable. I find it cleaner, and used it in the gradle integration.
The `TEMPLATE_PATH` environment variable can still be used, but should
probably be deprecated some time soon. Or do you guys like having both possibilities? I would vote for aiming at having one way to do a thing :-).
=> Add template_path as a parameter to protoc plugin

pb_plugins/dcsdkgen/type_info.py
In some languages (like Python), nested enums need to know their parent name. This adds it to type_info.
This is assuming only one level of nesting. It could probably be generalized, but we don't have such an example yet.
It also assumes (for now) that the package name has 3 levels (e.g. "org.dronecode.sdk"), but I believe I could solve that with the generalized nesting handling.
Required to fix [this issue](https://github.com/Dronecode/DronecodeSDK-Python/issues/47).
=> dcsdkgen: add parent_type to type info

pb_plugins/dcsdkgen/autogen.py
* Fix build for multiple proto files (previously it was returning after the first file)
* Improve error handling when protoc is run with the `file_ext` option missing
* Output java files in the right directory, according to java conventions (i.e. use the package)
=> Various fixes

protos/offboard/offboard.proto
One note, I see `NO_SETPOINT_SET` as part of the `Result` enum in the documentation for `develop` [here](https://sdk.dronecode.org/en/api_reference/classdronecode__sdk_1_1_offboard.html#classdronecode__sdk_1_1_offboard_1a1f515eed9d23c450254233ea87131c09), should this be explicitly returned [here](https://github.com/Dronecode/DronecodeSDK/blob/a2b9db92f83e53bcce75c611f6e9b473f4341562/plugins/offboard/offboard.cpp#L51-L70)?
=> Add Offboard Proto

protos/telemetry/telemetry.proto
Hey guys, I'm implementing the reading mavlink messages from the SDK and was wondering if this is the best way to do it. Please let me know what you think. 
Note that I tried to use `DEBUG` in the enum, but the compiler complained, so I'm using `DEBUS = 7;` for now, let me know what would be a good alternative word.
=> Add mavlink messages support.

protos/camera/camera.proto
This setting is no longer available.
See:
https://github.com/Dronecode/DronecodeSDK/pull/756
https://github.com/mavlink/mavlink/pull/1053
=> camera: remove set video stream settings

protos/offboard/offboard.proto
This is a corresponding PR to one made in DronecodeSDK [here](https://github.com/mavlink/MAVSDK/pull/782)
Python primitive types translates: https://github.com/mavlink/MAVSDK-Python/pull/76
=> Add direct control without specifying group names

.travis.yml, prototool.yaml
Adding a linter in Travis.
This will check that the proto files are well formed. More can be done with prototool (e.g. formatting), but this is a start.
=> add travis CI and prototool linter

protos/gimbal/gimbal.proto
Suggestion for initial idea of how set gimbal mode will look like.
For now it is working this way, but you guys might want to wait for: https://github.com/mavlink/mavlink/pull/1174 
Let's open a discussion here and see what to do.
=> Add gimbal mode support.

protos/telemetry/telemetry.proto
Added:
- AttitudeAngularSpeed: current angular speed from [ATTITUDE_QUATERNION](https://mavlink.io/en/messages/common.html#ATTITUDE_QUATERNION) message.
-   ActuatorControlTarget: current vehicle [attitude and body angular rates](https://mavlink.io/en/messages/common.html#SET_ACTUATOR_CONTROL_TARGET).
-  ActuatorOutputStatus: current raw values of the [actuator outputs](https://mavlink.io/en/messages/common.html#ACTUATOR_OUTPUT_STATUS).
Related PR in backend: https://github.com/mavlink/MAVSDK/pull/832
=> Added telemetry requests.

pb_plugins/protoc_gen_dcsdk/autogen.py, pb_plugins/protoc_gen_dcsdk/autogen_file.py, pb_plugins/protoc_gen_dcsdk/docs.py, pb_plugins/protoc_gen_dcsdk/enum.py, pb_plugins/protoc_gen_dcsdk/methods.py, pb_plugins/protoc_gen_dcsdk/struct.py, pb_plugins/protoc_gen_dcsdk/utils.py
This is adding the (admittedly) quite cryptic `docs.py` file, that tries to make sense of the comments in the proto files (based on documentation [here](https://github.com/protocolbuffers/protobuf/blob/a08b03d4c00a5793b88b494f672513f6ad46a681/src/google/protobuf/descriptor.proto)).
I believe this brings support for all the kind of documentation we currently need, including nested enums (one level only) and nested messages (which we currently don't use).
Resolves #91.
=> Parse documentation

protos/action/action.proto, protos/calibration/calibration.proto, protos/camera/camera.proto, protos/param/param.proto, protos/telemetry/telemetry.proto
Bring documentation from C++ to the proto files for a few plugins (action, calibration, camera, param, telemetry).
The other plugins will follow in a new PR soon.
@hamishwille: Those comments are the ones being parsed by #98 and used to generate language-specific documentation in the source files. I'll open a PR for the corresponding python templates as soon as those PRs are merged.
=> add documentation to proto files

pb_plugins/protoc_gen_dcsdk/type_info.py
This reverts commit b34da699d08a1e8c9376e3feb25433d128080798.
Removal of parent_type method in type_info.py will lead to syntax error in generated python codes after executing: ./other/tools/run_protoc.sh. The parent_type method is needed in struct.j2 (line 46 & 49), so it cannot be removed. 
Thanks
=> Revert "remove unused property"

protos/telemetry/telemetry.proto
Hi, I have added landed state support in telemetry, kindly note that the enum is with C++ scope, so I have to add a prefix LANDED_ to existing landed_state enum in order to differentiate with the UNKNOWN in FlightMode enum. 
I will try to add further support in MAVSDK and MAVSDK_python as well.
Thanks
coolkesword
=> add landed state in telemetry

protos/mocap/mocap.proto
This is a draft to MoCap plugin API implementation.
I allowed myself to move slightly away from the usual API. May be you will find it useful. 
Please let me know is that interface ok.
Links:
[External Positioning](https://dev.px4.io/v1.9.0/en/ros/external_position_estimation.html)
[VISION_POSITION_ESTIMATE](https://mavlink.io/en/messages/common.html#VISION_POSITION_ESTIMATE)
[MAVSDK PR](https://github.com/mavlink/MAVSDK/pull/850)
=> Initial MoCap service

protos/tune/tune.proto
Turns out the package for tune was set incorrectly, to geofence. I fixed it to mavsdk.rpc.tune so it generates correctly.
=> Fix package namespace for tune

.gitignore, pb_plugins/protoc_gen_dcsdk/struct.py, pb_plugins/protoc_gen_dcsdk/utils.py
This extracts the `default_value` from `FieldOptions` in struct.py, and assigns it to the params. As a result, the default value can be accessed in jinja2 templates with `param.default_value`.
=> Field options

pb_plugins/protoc_gen_dcsdk/autogen.py, pb_plugins/protoc_gen_dcsdk/enum.py
When an enum called SomeEnum has a value called SOME_ENUM_VALUE, we remove the prefix to keep VALUE for the templates.
=> Remove prefix in enum values

protos/calibration/calibration.proto
Tested to work with MAVSDK-Python (after corresponding changes)
=> Replace IN_PROGRESS and INSTRUCTION with more general NEXT

protos/shell/shell.proto
The existing API with sync and async command requests did not work for commands with continuous outputs like top. Therefore we changed this to a simple async stream of output plus a sync request to send a command line.
=> shell: autogenerate C++ plugin, change API

protos/mission_raw/mission_raw.proto
The templates in some languages (here Java) expect `*Result` to be formatted like `{{ plugin_name.upper_camel_case }}Result`.
=> MissionResult -> MissionRawResult

pb_plugins/protoc_gen_dcsdk/mavsdk_options_pb2.py, pb_plugins/protoc_gen_dcsdk/methods.py, protos/calibration/calibration.proto, protos/ftp/ftp.proto, protos/mavsdk_options.proto
This enables specifying if a stream is finite or not. For instance for calibration, a stream is finite and therefore the generation function is `_async` (e.g. `calibrate_accelerometer_async`). For telemetry, a stream is infinite and becomes `subscribe_` (e.g. `subscribe_position`).
This has an impact on all the streams (they all become `subscribe_`) except for `Calibration` and `FTP` plugins.
=> Add 'is_finite' option to methods

protos/ftp/ftp.proto, protos/offboard/offboard.proto
At first I was not aware that we could have requests without result, so I added them just for consistency. Here I'm removing it again.
=> Remove some unnecessary results

pb_plugins/protoc_gen_dcsdk/autogen.py, protos/log_files/log_files.proto
* Java has different package names, so `autogen.py` needs to take that into account when ignoring files.
* The result type is hardcoded in Java, so it must be `<plugin_name.upper_camel_case>Result` in the proto file as well.
* The return name (here was `log_file_result` instead of `log_files_result`) should not require that, but it's faster to fix the Java autogen like this, and it doesn't hurt in the proto files.
* The languages bindings assume that a stream finishes on `SUCCESS`, gets an element on `NEXT`, and errors on everything else. Hence, `PROGRESS` is considered an error and should really be called `NEXT`.
Note that these changes should not have any influence in the compatibility between `mavsdk_server` and the language bindings: it's really just naming, but on the proto transport …
=> minor fixes for MAVSDK-Java autogen

protos/calibration/calibration.proto
This adds the level horizon calibration to be used on the different client languages.
=> calibration: add board level horizon to proto

protos/calibration/calibration.proto
To notify on failure because the vehicle is armed. To address https://github.com/mavlink/MAVSDK/pull/1096#discussion_r423745374.
=> calibration: add RESULT_FAILED_ARMED

protos/geofence/geofence.proto
`Type` is a reserved word in Swift, so the proposition here is to avoid it. It could be dealt with, if really necessary, by using backticks around all the generated types. But in this case it feels like renaming it is not too bad.
It won't break protobuf compatibility, since it's just a name change.
=> Rename `Type` to `FenceType`

protos/ftp/ftp.proto, protos/tune/tune.proto
For instance, "id" becomes "ID" sometimes, and "Id" other times. Which makes it hard for our auto-generation. Let's use "index" instead of "id" then.
Also, `description` becomes `description_p` for some reason, so I renamed it to `tune_description`.
=> Swift protobuf is giving inconsistent results with some acronyms

protos/offboard/offboard.proto
https://github.com/mavlink/MAVSDK/issues/1154 
`set_velocity_ned` and `set_velocity_body` doesn't work as outlined in the [px4 documentation](https://docs.px4.io/master/en/flight_modes/offboard.html#fixed-wing). This PR adds some information regarding this into the `offboard` plugin.
=> Update offboard set velocity documentation

protos/telemetry/telemetry.proto
This adds support for GPS_GLOBAL_ORIGIN through MAV_CMD_REQUEST_MESSAGE.
=> Add GpsGlobalOrigin to Telemetry

protos/action/action.proto
Side note the enum in the documentation has behavior spelled as behaviour for Orbit_Yaw_Behaviour [here](https://mavlink.io/en/messages/common.html).
=> Added comment for Orbit Yaw Behavior enum.

protos/gimbal/gimbal.proto
To be consistent, the messages will be available when the gimbal implements v1, but they will always succeed (so that the client can write the same code for both versions).
Secondary mode is not yet supported, and will return a `Gimbal::Result::Unsupported` immediately.
=> Add control messages for gimbal v2

protos/camera/camera.proto
Otherwise this can cause name collisions for certain languages.
=> camera: disambiguate the status enum and struct

protos/tracking_server/tracking_server.proto
That's needed at least for Java :sweat_smile:
=> Result name needs to correspond to the result type

protos/calibration/calibration.proto
And this should make it more consistent with other request/responses.
=> calibration: cancelling can fail

pb_plugins/requirements.txt
Otherwise we can end up with protobuf with a too old version.
=> pb_plugins: fix requirements version

pb_plugins/protoc_gen_mavsdk/docs.py
When parsing the docs, the script is creating its own struct to keep the documentation. When it finds a new nested enum, it creates a new dictionary to save its values. Until now, we never had more than two nested enums together, so the script worked, but the second nested enum actually erases the first one and the code crashes.
FYI @markusachtelik
=> Only create the dictionary when it does not exist

protos/camera/camera.proto
[outdated:]
This PR adds the interfaces to subscribe to VIDEO_STREAM_STATUS messages from the camera. https://mavlink.io/en/messages/common.html#VIDEO_STREAM_STATUS 
[new]
after discussions, we decided to not duplicate the redundant mavlink messages VIDEO_STREAM_STATUS and VIDEO_STREAM_INFORMATION. Instead, we extend the current structure, and update it whenever data from either of these messages arrives. 
PR in mavsdk will follow. 
@julianoes , @JonasVautherin  can you take a look?
=> Added horizontal FOV and videostream light spectrum enum

.github/workflows/main.yml, pb_plugins/setup.py
Note: setup.py does not get the version from the tag, it will just push whatever is there. So we need to make sure it's correct before we tag it. An improvement could be to have setup.py take the version number as an optional argument, and have the CI pass it when building a tag.
=> Bump to 1.0.1 and add deploy CI job

protos/tune/tune.proto
This always just triggered a warning.
=> tune: remove unused options

protos/mission/mission.proto, protos/mission_raw/mission_raw.proto
This moves the method to import QGroundControl .plan JSON mission files from the mission plugin to the mission_raw plugin.
The reasoning is as follows:
The imported missions did not really fit the Mission API, and I guess that the mission progress was often wrong.  When the missions were imported into mission, many items/commands were unsupported and dropped with a warning. Such a warning is not visible in the language wrappers and could lead to surprises. The documentation said that the method would fail if any unsupported item was being imported, however, that was not true anymore in code.
Therefore, in my opinion, it makes a lot more sense to implement the import in mission_raw where all/any mission items and commands can be imported. It's should be more complete, without surprises, …
=> Move QGC import from mission to mission_raw

protos/log_files/log_files.proto
MAVSDK needs to `get_entries()` before it can download log files. But it seems like users tend to hardcode the log file value and get confused with the error code. This puts a dependency on `get_entries()`, such that the code won't compile if it is not called.
=> SubscribeDownloadLogFile should depend on GetEntries to avoid confusion

protos/camera/camera.proto
For a survey app, in order to compute the overlap between images, one needs the sensor information, which is not exposed yet. 
@julianoes Or is it exposed somewhere else and I missed it?
=> Expose camera sensor information

protos/core/core.proto
Is it already not being used by `mavsdk_server`, defaulting to 0. This change will remove it from the interfaces in the language bindings (no change is needed anywhere else).
=> Remove uuid from core, replaced by identification in info

protos/camera/camera.proto, protos/ftp/ftp.proto, protos/geofence/geofence.proto, protos/gimbal/gimbal.proto, protos/info/info.proto, protos/log_files/log_files.proto, protos/mission/mission.proto, protos/mission_raw/mission_raw.proto, protos/param/param.proto, protos/tune/tune.proto
This adds the result for when no system is connected to all plugins that did not previously have that. This is required in mavsdk_server if no system is connected but we still need to answer something over gRPC.
=> protos: add RESULT_NO_SYSTEM to all plugins

protos/telemetry/telemetry.proto
We always just faked level calibration to be true/ok. Also, a level calibration is not actually required or enforced anywhere, so there is little value in checking it as a preflight check with MAVSDK.
=> telemetry: remove level health check

protos/telemetry/telemetry.proto
Added id field to Battery message.
In preparation for a PR in the MAVSDK repo that will enable handling of multiple batteries.
=> telemetry: Added id field to Battery message.

protos/action_server/action_server.proto
Add server side functionality for `action` plugin - moved out of `telemetry_server` proto and expanded
`ArmDisarm` handles `Kill` `Arm` `Disarm`
`FlightModeChange` handles vehicle flight modes requests from `DO_SET_MODE`
Others for parity with the `Action` plugin
I'm not too happy with having to manage the state with Getters and Setters, it's a bit of a hack for now to allow for handling of Arming and Flightmode changing. 
Longer term we should review the autogeneration here to allow a callback to handle the acceptance or denial of a request - removing the need for the state.
=> Add action_server proto

protos/camera/camera.proto
Plugins are lazily initialized in mavsdk_server. This allows to manually initialize the camera plugin (and have it download the camera definition file, etc).
=> Add prepare() to camera plugin

protos/mission/mission.proto
This enables to set the trigger distance as part of the mission.
=> mission: add way to set up trigger distance

protos/camera/camera.proto
Is it ok not to populate all enum options in `STORAGE_TYPE`?
=> camera: add storage ID and type

pb_plugins/protoc_gen_mavsdk/methods.py
When defining a rpc function with a return stream, it is necessary that
this function returns something that is not a *Result. So the Response
proto must contain more than just the result entry. Here we give an
explicit error message, so that the developer knows precisely what is
missing.
=> protoc_gen_mavsdk: error on missing return value

protos/calibration/calibration.proto
This is handy to signal if something is not expected to work for a flight stack.
=> calibration: add unsupported result

protos/mocap/mocap.proto
This should be handy to indicate support for a feature.
=> mocap: add unsupported result

protos/camera/camera.proto
This adds a new function to the camera plugin will change current camera-id managed by the Camera plugin instance.
This PR is related to the this other ([PR](https://github.com/mavlink/MAVSDK-Proto/pull/274)) that aim to add the multi-camera capability to the Camera plugin
=> camera: Added select_camera function

protos/action/action.proto
This is different from the maximum speed as the maximum speed setting isbasically a param that gets set and saved on the  vehicle while this is just temporary for the current flight.
=> action: add API to set current speed

protos/action/action.proto, protos/mission/mission.proto, protos/mission_raw/mission_raw.proto, protos/offboard/offboard.proto
This comes with the extension of the MAVLink command sender.
=> Add some more result options

pb_plugins/protoc_gen_mavsdk/autogen.py, pb_plugins/protoc_gen_mavsdk/autogen_file.py, pb_plugins/protoc_gen_mavsdk/enum.py, pb_plugins/protoc_gen_mavsdk/methods.py, pb_plugins/protoc_gen_mavsdk/name_parser.py, pb_plugins/protoc_gen_mavsdk/struct.py, pb_plugins/protoc_gen_mavsdk/type_info.py, pb_plugins/protoc_gen_mavsdk/utils.py, pb_plugins/setup.py
* Make sub-template files (e.g. enum.j2, struct.j2, ...) optional
* Expose everything to root template (enabling single-template definitions)
* Add more command arguments, giving more control about e.g. the output file or the root template file.
Tested in MAVSDK and MAVSDK-Python: generating the code with this version does not change anything :+1:.
Those changes are used in https://github.com/JonasVautherin/protoc-gen-mavsdk-example.
=> Various improvements

protos/telemetry/telemetry.proto
Before we processed whatever attitude was being sent which meant that both MAVLink messages ATTITUDE and ATTITUDE_QUATERNION would trigger both callbacks. This was often ok but can be very confusing when trying
to set the rate of the messages.
This commit decouples this magic and provides setters for both the rates.
=> telemetry: split attitude into Euler + Quaternion

protos/telemetry/telemetry.proto
This pull request would close [#1903](https://github.com/mavlink/MAVSDK/issues/1903).
=> Added altitude to telemetry plugin

protos/mission_raw/mission_raw.proto
This enables to import mission plan files without having to write them to some location first.
=> mission_raw: add method to import plan from string

protos/telemetry/telemetry.proto
I am interested in receiving more information about the battery status through MAVSDK. Mainly I need the current consumption, but I took the opportunity to add the other information.
- temperature
- current_battery
- current_consumed
- energy_consumed
I don't see the _temperature_ and _energy_consumed_ in my flight logs so not sure if it is relevant to add them. I also saw that there was already a PR in progress for adding messages for the v2 battery but nothing done for v1 from what I found.
=> PR Add battery proto status message for v1

protos/camera/camera.proto
This is required to support builds without CURL. So if CURL is not built in, then http URIs will just return ResultProtocolUnsupported.
Signed-off-by: Julian Oes <julian@oes.ch>
=> camera: add result when protocol is not supported

pb_plugins/setup.py
This mainly changes the max protobuf version to 3.20.1 which should fix the versioning nightmare with docs.
Signed-off-by: Julian Oes <julian@oes.ch>
=> protoc-gen-mavsdk: bump version to 1.1.1

protos/telemetry/telemetry.proto, protos/telemetry_server/telemetry_server.proto
- Proto: https://github.com/mavlink/MAVSDK-Proto/pull/310 **(this PR)**
- MAVSDK: https://github.com/mavlink/MAVSDK/pull/1964 
The DistanceSensor is already part of telemetry and telemetry_server. The subscriber was implemented in telemetry, but the publisher in telemetry_server is missing.
I would like to add a publisher for [DISTANCE_SENSOR](https://mavlink.io/en/messages/common.html#DISTANCE_SENSOR) to MAVSDK. 
The question is also whether we should include the full message spec while at it. The missing fields that exist in mavlink but not in the proto definition of DistanceSensor are:
- Type (MAV_DISTANCE_SENSOR)
- ID
- Orientation (MAV_SENSOR_ORIENTATION)
- Covariance
- Horizontal FOV
- Vertical FOV
- Quaternion for orientation
- Signal Quality
Does it make sense to add all of them …
=> Add PublishDistanceSensor to Telemetry Server

protos/gripper/gripper.proto, protos/winch/winch.proto
- Proto: https://github.com/mavlink/MAVSDK-Proto/pull/308 **(this PR)**
- MAVSDK: https://github.com/mavlink/MAVSDK/pull/1958
- MAVSDK-Python: MAVSDK-Python: https://github.com/mavlink/MAVSDK-Python/pull/545 
Message definitions for Winches and Grippers. This reflects the following mavlink messages:
- MAV_CMD_DO_GRIPPER [(211)](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_GRIPPER)
- MAV_CMD_DO_WINCH ([42600](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_WINCH) )
and their submessages for the gripper and winch actions, as well as the winch status.
Please don't merge before I squashed the commits
=> Winch and Gripper plugins

protos/gripper/gripper.proto, protos/winch/winch.proto
Slipped through the cracks in the previous PR: https://github.com/mavlink/MAVSDK-Proto/pull/308
Addresses the following CI failure over in MAVSDK:
```
2023-01-31T13:50:06.1606188Z Preprocessing /home/runner/work/MAVSDK/MAVSDK/tools/docs/install/include/mavsdk/plug/home/runner/work/MAVSDK/MAVSDK/tools/docs/install/include/mavsdk/plugins/winch/winch.h:91: warning: Compound mavsdk::Winch::StatusFlags is not documented.
2023-01-31T13:50:06.1606831Z /home/runner/work/MAVSDK/MAVSDK/tools/docs/install/include/mavsdk/plugins/winch/winch.h:28: warning: Compound mavsdk::Winch is not documented.
2023-01-31T13:50:06.1607356Z /home/runner/work/MAVSDK/MAVSDK/tools/docs/install/include/mavsdk/plugins/gripper/gripper.h:28: warning: Compound mavsdk::Gripper is not documented.
2023-01-31T13:50:06.1607877Z …
```
=> Add missing documentation for winch/gripper plugins

.github/workflows/main.yml
It looks like the 18.04 containers didn't start no longer.
=> workflows: update GitHub runner and prototool

protos/param/param.proto
This should allow to create param plugins to talk to specific components.
This replaces the `param->late_init()` suggested in https://github.com/mavlink/MAVSDK/pull/1809 by @Consti10.
=> param: allow to set component ID and protocol

protos/offboard/offboard.proto
I have added option to send acceleration as well by creating a function called drone.offboard.set_position_velocity_acceleration_ned(
PositionNedYaw(*position, yaw),
VelocityNedYaw(*velocity, yaw),
AccelerationNed(*acceleration)
)
it still has problems
steps I did:
forked mavsdk and mavsdk proto.
edited the proto files for my new message and function
added the  cpp functions and edit cpp and h files in mavsdk src
```
Offboard::Result OffboardImpl::send_position_velocity_acceleration_ned()
{
const static uint16_t IGNORE_YAW_RATE = (1 << 11);
std::lock_guard<std::mutex> lock(_mutex);
mavlink_message_t message;
mavlink_msg_set_position_target_local_ned_pack(
_system_impl->get_own_system_id(),
_system_impl->get_own_component_id(),
&message, …
```
=> added pos,vel,acc offboard

protos/camera_server/camera_server.proto
1、Add start stop video subscribe in camera server.
Please check this function and don't need merge for now.
=> Add more camera function

protos/camera_server/camera_server.proto
This reverts:
"camera server : add start stop video subscribe (#318)"
We will add it back in shortly. This is just because the PR following this has not been merged.
This reverts commit 8966cf59029ac17d81654071ca6d3d27f0d8897d.
@tbago I'll bring the changes back in soon. I just need to finish the FTP stuff first.
=> Revert recent camera_server additions

protos/telemetry/telemetry.proto
Added orientation parameter to telemetry.distance_sensor to take advantage of the mavlink orientation parameter and receive measurements for multiple distance sensors
=> Customizing distance sensor to add orientation for multiple sensor support

protos/gimbal/gimbal.proto
This feature is a request as I have to use the gimbal I have in a certain way and the roll and pitch axis are switched.
As the pitch of the payload of the gimbal is vitally important, this feature is needed.
=> Full gimbal angle control

protos/camera/camera.proto
From this PR -> https://github.com/mavlink/MAVSDK/pull/2094#issuecomment-1610226707
This repository add the camera function to proto
=> feature zoom focus tracking

protos/arm_authorizer_server/arm_authorizer_server.proto
This PR adds the functionality of arm authorization server, as it is described by [MavLink arm authorization protocol](https://mavlink.io/en/services/arm_authorization.html). The server should be able to respond to `MAV_CMD_ARM_AUTHORIZATION_REQUEST` with a user specified callback and allow or reject arming, requested by a vehicle. I also created a [PR into MAVSDK](https://github.com/mavlink/MAVSDK/pull/2267) with a C++ implementation and example
=> Added arm authorization server functionality

protos/log_streaming/log_streaming.proto
This adds ulog log streaming, in base64.
=> Add log_streaming

protos/ftp/ftp.proto
This way we get a clear list of files and folders instead of an odd list with F or D prefixes.
=> ftp: split list_directory response

protos/rtk/rtk.proto
This makes it possible to use this via other languages like Python where binary data in a string is not an option.
=> rtk: encode RTCM data in base64

protos/log_streaming/log_streaming.proto
This way it's harder to miss this.
=> log_streaming: make base64 format clearer

protos/telemetry/telemetry.proto
This was always confusing. The data should instead be queried from the gimbal plugin.
=> telemetry: remove camera attitude

protos/gimbal/gimbal.proto
- Adding an argument for send mode (either command or message stream)
- Includes the mode into the setter because that's when it's sent.  Otherwise, the set_mode call itself doesn't have any effect which is not very intuitive.
- Extend interface to support multiple gimbals.
=> Gimbal API redesign (support more than one gimbal, support streams and commands)

protos/camera_server/camera_server.proto
PR associated with this change:
https://github.com/mavlink/MAVSDK/pull/2351
=> camera-server: Add ability to support taking image in video mode and video in image mode

.github/workflows/main.yml
=> CI: bump upload-artifact version

protos/action/action.proto
This API is confusing as it only works for PX4 quads but not PX4 fixedwing or anything ArduPilot based.
The reason is that this just sets a PX4 parameter that is not standardized via MAVLink.
Therefore, I suggest to remove the API and instead recommend to use the param plugin to set the specific params specifically.
=> action: remove max speed settings

protos/camera/camera.proto, protos/gimbal/gimbal.proto, protos/param_server/param_server.proto
This changes the API to support more than one camera within one camera plugin instance.
This will enable multiple cameras in language wrappers instead of just C++ as it is now.
=> camera: change API to support multiple cameras

protos/mission_raw_server/mission_raw_server.proto
This is a companion PR for the main implementation in MAVSDK:
https://github.com/mavlink/MAVSDK/pull/2463
Details can be found in the MAVSDK PR.
=> API for receiving status notifications on outgoing mission requests

protos/mission_raw_server/mission_raw_server.proto
I made a mess and need to revert this one for now.
This reverts commit c6089e77eb621ceee89a7d528444bd19de6983ec.
=> Revert "Added API for receiving status notifications on outgoing mission requests"

protos/mission_raw_server/mission_raw_server.proto
PR #352 introduced breaking changes for MAVSDK main. The MAVSDK PR that would fix that is here, and has been open since august: https://github.com/mavlink/MAVSDK/pull/2386. In order to be able to make changes to the submodule on MAVSDK main without requiring MAVSDK 2386 to merge, these changes will need to be reverted.
=> mission_raw_server: make subscriptions async only

.gitignore, pb_plugins/protoc_gen_mavsdk/__init__.py, pb_plugins/protoc_gen_mavsdk/__main__.py, pb_plugins/protoc_gen_mavsdk/autogen.py, pb_plugins/protoc_gen_mavsdk/autogen_file.py, pb_plugins/protoc_gen_mavsdk/docs.py, pb_plugins/protoc_gen_mavsdk/mavsdk_options_pb2.py, pb_plugins/protoc_gen_mavsdk/methods.py, pb_plugins/protoc_gen_mavsdk/name_parser.py, pb_plugins/protoc_gen_mavsdk/pb_enum.py, pb_plugins/protoc_gen_mavsdk/pb_struct.py, pb_plugins/protoc_gen_mavsdk/struct.py, pb_plugins/protoc_gen_mavsdk/utils.py, pb_plugins/requirements.txt, pb_plugins/setup.py, pb_plugins/test/test_name_parser.py, pb_plugins/test/test_type_info.py
Whilst attempting to fix issues within MAVSDK-Python outlined [here](https://github.com/mavlink/MAVSDK-Python/issues/698), I noticed dependency conflicts arising from the fact that the `pb_plugin` utilises very old versions of `protobuf`.
Updated those dependencies and formatted the project. Also fixed a few failing tests
=> Updated proto `pb_plugin`

pb_plugins/setup.py
This is needed for deployment, otherwise it tries to overwrite 1.1.1 and fails (see [here](https://github.com/mavlink/MAVSDK-Proto/actions/runs/12862022784/job/36055095760)) 👍.
=> Bump to 1.2.0

protos/telemetry/telemetry.proto, protos/telemetry_server/telemetry_server.proto
Changes to support the corresponding MAVSDK PR: https://github.com/mavlink/MAVSDK/pull/2504
Specifically:
- Filled out the FixedwingMetrics struct to include the rest of the fields in the MAVLINK VFR_HUD message
- Added an Attitude message for the TelemetryServer for symmetry with the Telemetry class
Note that currently MAVSDK does not build against Proto main. The MAVSDK PR listed above is using a branch of Proto with changes cherry-picked.
=> Telemetry and TelemetryServer improvements

protos/action_server/action_server.proto
The `ActionServer` implementation currently only supports updating arm/disarm status and flight mode by receiving MAVLINK messages from a client. An autopilot implementation may need to take autonomous action to change flight modes or report an armed status apart from explicit GCS command. This PR provides the necessary support to do that.
=> ActionServer: allow direct setting of arm/disarm state and vehicle flight mode

protos/telemetry/telemetry.proto
These are - by the MAVLink spec - just raw, without unit. Our types are misleading and wrong. The least we can do is to flag this as incorrect.
For the next release we should probably remove this debug telemetry feature.
=> telemetry: add comment regarding RawImu units
