mavlink/MAVSDK-Proto

action/action.proto

define action protocol

---

telemetry/telemetry.proto

define telemetry protocol

---

mission/mission.proto

define mission protocol

---

gimbal/gimbal.proto

define gimbal protocol

---

core/core.proto

It fixes "missing field name" issue

Add missing field name in core proto file

---

action/action.proto
discovery/discovery.proto

Reference: https://github.com/dronecore/DroneCore/issues/318

Replace Device -> System

---

camera/camera.proto

Connects to https://github.com/dronecore/DroneCore/issues/334.

update camera according to new c++ interface

---

action/action.proto

This adapts the proto file after the action getter/setter API has changed.
Related to https://github.com/Dronecode/DronecodeSDK/pull/449.

action: return error codes for getter/setter

---

camera/camera.proto

camera: always pass setting description

---

pb_plugins/dcsdkgen/__main__.py
pb_plugins/dcsdkgen/autogen.py
pb_plugins/dcsdkgen/enum.py
pb_plugins/dcsdkgen/methods.py
pb_plugins/dcsdkgen/utils.py
pb_plugins/templates/swift/method_completable.j2
pb_plugins/templates/swift/method_observable.j2
pb_plugins/templates/swift/method_single.j2

Add parsing for method parameters
@xvzf: Please have a look ;-)

Handle method params

---

pb_plugins/dcsdkgen/methods.py

Moved to dataclass for easier handling and better readability

---

protos/action/action.proto
protos/camera/camera.proto
protos/mission/mission.proto

* GetReturnToLaunchAfterMission / SetReturnToLaunchAfterMission
* GetReturnToLaunchAltitude / SetReturnToLaunchAltitude
* recording_time_s for CameraStatus
* loiter_time for MissionItem

Add various features

---

protos/camera/camera.proto

camera: added media folder name

---

pb_plugins/dcsdkgen/methods.py

@JonasVautherin Please review just in case I broke anything!

Removed datalcass so the autogenerator can be run with Python3.6

---

pb_plugins/dcsdkgen/enum.py
pb_plugins/dcsdkgen/methods.py
pb_plugins/dcsdkgen/name.py
pb_plugins/dcsdkgen/struct.py
pb_plugins/dcsdkgen/utils.py

Untested. What do you think @JonasVautherin 
Fixes #46.

Added name class

---

pb_plugins/dcsdkgen/enum.py
pb_plugins/dcsdkgen/methods.py
pb_plugins/dcsdkgen/name_parser.py
pb_plugins/dcsdkgen/struct.py
pb_plugins/dcsdkgen/type_info.py
pb_plugins/dcsdkgen/utils.py

While generating Swift files, I came accross a few bugs in the autogenerator. This is not affecting anything in the c++ backend autogeneration (I haven't looked at the python files yet).

Various bug fixes in autogenerator

---

pb_plugins/dcsdkgen/name_parser.py

That's a detail, but it was bothering me.

snake_case should be upper_snake_case for consistency

---

pb_plugins/dcsdkgen/methods.py
pb_plugins/dcsdkgen/struct.py
pb_plugins/dcsdkgen/type_info.py
pb_plugins/dcsdkgen/utils.py
pb_plugins/test/test_type_info.py

Loading the file statically is not nice for unit testing. But loading the file for each instantiation doesn't sound right either. So I made a factory for that, that loads the file only once.

Test type info

---

protos/mission/mission.proto

Those are covered by SubscribeMissionProgress.
@julianoes: I checked with 3DR and they don't use them.

mission: remove superfluous functions 

---

protos/mission/mission.proto

For some reason it was not there :sweat_smile:.

mission: add camera_photo_interval parameter to MissionItem

---

protos/calibration/calibration.proto
protos/mission/mission.proto

- Add cancel calibration wrapper.
- Add cancel mission download wrapper.
- Add cancel mission upload wrapper.

Add wrappers for cancel calibration, mission download, and mission upload.

---

protos/mission/mission.proto

Anything else that needs to be added for this?

mission: add missing result

---

protos/offboard/offboard.proto

This is a corresponding PR to one made in  DronecodeSDK [here](https://github.com/Dronecode/DronecodeSDK/pull/743)

added SetAttitude method with corresponding messages

---

README.md
pb_plugins/README.rst
pb_plugins/protoc_gen_dcsdk/__init__.py
pb_plugins/protoc_gen_dcsdk/autogen.py
pb_plugins/setup.py

Renamed DronecodeSDK to MAVSDK

---

pb_plugins/protoc_gen_dcsdk/type_info.py
protos/action/action.proto
protos/calibration/calibration.proto
protos/camera/camera.proto
protos/core/core.proto
protos/gimbal/gimbal.proto
protos/info/info.proto
protos/mission/mission.proto
protos/offboard/offboard.proto
protos/param/param.proto
protos/telemetry/telemetry.proto

protos: rename dronecode_sdk -> mavsdk

---

protos/offboard/offboard.proto

@avdwerff: That's the reason for your build error.

fix spelling: NED -> Ned

---

protos/mission/mission.proto

Implementation of [Mission: provide API to clear mission](https://github.com/mavlink/MAVSDK/issues/663)

Add clear mission.

---

protos/telemetry/telemetry.proto

Due to https://github.com/mavlink/MAVSDK/pull/866

Telemetry Odometry stream added

---

protos/mocap/mocap.proto

Due to https://github.com/mavlink/MAVSDK-Proto/pull/105#discussion_r334379895

MoCap Odometry::MavFrame enum values change

---

protos/shell/shell.proto

My attempt to implement MAVLink shell.
Corresponding MAVSDK PR: https://github.com/mavlink/MAVSDK/pull/878
Corresponding MAVSDK-Python PR: https://github.com/mavlink/MAVSDK-Python/pull/120

Shell plugin

---

protos/shell/shell.proto

Due to https://github.com/mavlink/MAVSDK/pull/944

Added NOT_COMPLETED Result enum member in Shell proto

---

protos/telemetry/telemetry.proto

This update for MANUAL, ALTITUDE CONTROL, POSITION CONTROL, ACRO, STABILIZED and RATTITUDE modes.
Regarding of this PR [Additional Flight Modes](https://github.com/mavlink/MAVSDK/pull/942/)

update for PX4 Flight Modes

---

protos/tune/tune.proto

Rather simple proto file, for the tune plugin...
Let me know if something should be changed.

Add tune proto

---

protos/followme/followme.proto

Here's an attempt at creating the proto files for the FollowMe plugin.
Please let me know if anything needs to be changed!

Add followme proto

---

protos/telemetry/telemetry.proto

@irsdkv: Would you mind helping me with the 4 `TODO`s I left in this PR? I don't really know what they are :innocent:.

fix telemetry documentation

---

protos/telemetry/telemetry.proto

This is adding (most) of the remaining C++ features of the telemetry plugin.

update telemetry.proto in the context of c++ autogeneration

---

protos/action/action.proto

Otherwise this extra star appears in the generated documentation.
@julianoes: FYI

remove extra star in documentation comments

---

protos/geofence/geofence.proto

All that was needed for geofence.

geofence: adapt to new enum prefix convention

---

protos/geofence/geofence.proto

geofence: add missing comment

---

protos/calibration/calibration.proto

Changes for calibration autogen

---

protos/param/param.proto

This adds the sync only option and changes the method naming to be consistent with C++.

Autogenerate param plugin

---

protos/mission_raw/mission_raw.proto

MissionRaw is coming to all the languages!
FYI @sanderux

Add proto file for MissionRaw

---

protos/mocap/mocap.proto

Autogenerate mocap plugin.

---

protos/follow_me/follow_me.proto
protos/info/info.proto
protos/tune/tune.proto

Needed in Java. Since those are the only remaining ones, I thought we could go on with those changes already...
Or we can put it on hold and I stay on the branch in MAVSDK-Java, but I think it should not cause issues.

Enum prefixes

---

protos/action/action.proto
protos/calibration/calibration.proto
protos/camera/camera.proto
protos/follow_me/follow_me.proto
protos/ftp/ftp.proto
protos/geofence/geofence.proto
protos/gimbal/gimbal.proto
protos/info/info.proto
protos/log_files/log_files.proto
protos/mission/mission.proto
protos/mission_raw/mission_raw.proto
protos/offboard/offboard.proto
protos/param/param.proto
protos/shell/shell.proto
protos/telemetry/telemetry.proto

This improves a few things that caught my eye.

protos: pass over result description

---

protos/telemetry/telemetry.proto

These two types were duplicate so it made sense to merge them.

telemetry: merge SpeedNed into VelocityNed

---

protos/gimbal/gimbal.proto

Work in progress for gimbal V2 protocol.

gimbal: changes for protocol v2

---

protos/geofence/geofence.proto

Fix after https://github.com/mavlink/MAVSDK-Proto/pull/156.

geofence: fix fence type again

---

protos/failure/failure.proto
protos/info/info.proto

This plugin can be used to inject failures into the system.

Add failure plugin and lockstep speed factor info

---

protos/telemetry/telemetry.proto

Continuation of https://github.com/mavlink/MAVSDK/pull/1102.

Add all MAVLink STATUSTEXT severity enum values to StatusTextType

---

protos/action/action.proto

That's the new function I added in the devsummit 2020 demo

Add terminate for devsummit demo

---

protos/param/param.proto

There is no possibility to get all parameters with MAVSDK at the moment. This PRs intend is prepare its implementation.

Add GetAllParams proto

---

protos/telemetry/telemetry.proto

Added API for distance sensor in telemetry plugin.

Added API for distance sensor in telemetry plugin.

---

protos/manual_control/manual_control.proto

Follow up to https://github.com/mavlink/MAVSDK/pull/1251

manual_control: add result for no input set

---

.github/workflows/main.yml
README.md

Also see https://github.com/github/renaming.

Rename master branch to main

---

protos/tracking_server/tracking_server.proto

This adds a plugin for onboard tracking software.

Add tracking_server plugin

---

protos/camera/camera.proto

Probably need some work on the wording, but you get the idea :sweat_smile:.
I am also considering having a LAST_MISSION range, that would list the images taken during the last mission (current mission if not finished).

Add a way to list photos from camera plugin

---

pb_plugins/protoc_gen_mavsdk/type_info.py
pb_plugins/test/test_type_info.py

This is required for my Swift try.

pb_plugins: add property is_string

---

protos/server_utility/server_utility.proto

This should be a plugin for common tasks required when running MAVSDK onboard a companion computer.

Add ServerUtility plugin

---

protos/action/action.proto

Serves the sole purpose of making available a command to easily trigger a hold action on the vehicle.

action: add request for vehicle to hold position (loiter)

---

protos/transponder/transponder.proto

Attempting to get the process started on getting this capability implemented.
Thanks.

Create plugin for ADS-B transponder communication

---

protos/action/action.proto

@julianoes Just rebased the previous actuator PR onto main, since the feature is merged in PX4 now. If this looks good I'll do the same to the C++ library PR.

Add set actuator

---

protos/mission/mission.proto

Adding acceptance radius back in via proto

Add Acceptance radius to mission proto

---

protos/telemetry/telemetry.proto

Small telemetry improvements

---

pb_plugins/README.rst

Fix example protoc command

---

.github/workflows/lint_python.yml
protos/camera/camera.proto
protos/follow_me/follow_me.proto
protos/param/param.proto
protos/telemetry/telemetry.proto

Output: https://github.com/cclauss/MAVSDK-Proto/actions

GitHub Action to lint Python code

---

protos/telemetry/telemetry.proto

This should come in handy when you need to know if you can arm the
system.

telemetry: add armable flag to health

---

protos/param_server/param_server.proto

API for setting/getting the parameters in MAVSDK as a parameter server.
Implementation Here: https://github.com/mavlink/MAVSDK/pull/1473

Add param_server

---

protos/mission/mission.proto

This allows to assume a specific, absolute yaw angle at a waypoint.

mission: add yaw angle

---

protos/telemetry_server/telemetry_server.proto

Add telemetry server proto.
This is based on the existing telemetry proto subscriptions - with some removals.

Add telemetry_server proto

---

protos/telemetry_server/telemetry_server.proto

- Made publish messages `SYNC`
- Removed unneeded rpcs from the `telemetry_server.proto` 
- Added support for more telemetry message types (`sys_status`, `extended_sys_state`)
- VTOL types
- RC receiver types
~Added Vehicle Arming~ Moved to `action_server` - https://github.com/mavlink/MAVSDK-Proto/pull/244
~Added Flight_modes~ Moved to `action_server` - https://github.com/mavlink/MAVSDK-Proto/pull/244

Revise telemetry_server - Add sys_status

---

protos/mission_raw_server/mission_raw_server.proto
protos/mission_server/mission_server.proto

Add types required for mission_server.

Add Mission server

---

protos/telemetry/telemetry.proto

There was no way to get information from MAVSDK if vehicle is in VTOL or Fixed-wing mode.

Add VTOL state subscribe

---

protos/mission/mission.proto

@rligocki FYI, I brought the PR back until the work in MAVSDK-C++ is finished :+1:

Add vehicle action

---

protos/telemetry/telemetry.proto
protos/telemetry_server/telemetry_server.proto

The enum name needs to be repeated like that.

Fix VTOL state enum

---

protos/telemetry/telemetry.proto

Added information of the current vtol state to the telemetry plugin

added vtol state to telemetry (follow up)

---

protos/mission/mission.proto

We can add it back in after this release and finish the feature.
FYI @rligocki.

mission: remove VehicleAction for now

---

protos/action_server/action_server.proto
protos/mission_raw_server/mission_raw_server.proto
protos/param_server/param_server.proto

This should have no impact on C++, but the inconsistencies in the proto files were breaking the java build. Those things could be enforced by protoc-gen-mavsdk, but I would need to spend some time on it.

Fix protos for java

---

protos/offboard/offboard.proto

proto for [PR-1620](https://github.com/mavlink/MAVSDK/pull/1620)

proto for offboard global position

---

protos/offboard/offboard.proto

I added an altitude type for the offboard global position

proto for offboard global pos altitude type

---

protos/component_information/component_information.proto
protos/component_information_server/component_information_server.proto

This is a start to create an example which is a component. This then allows us to test a ground station against a component.

Add component information client and server

---

protos/action/action.proto

This is nice to have in case action functionality is not supported.

action: add unsupported result

---

protos/transponder/transponder.proto

related to https://github.com/mavlink/MAVSDK/pull/1730

Transponder: add tslc in AdsbVehicle

---

protos/transponder/transponder.proto

I'm always picky on units :grin:.

transponder: don't forget unit

---

protos/log_files/log_files.proto

Accompanying proto files for https://github.com/mavlink/MAVSDK/pull/1649.

proto for erasing log files and synchronous log file download

---

protos/rtk/rtk.proto

This adds a plugin to send RTCM correction data for RTK GPS.

Add RTK plugin

---

protos/param/param.proto
protos/param_server/param_server.proto

This adds support for custom string params up to 128 bytes.

param/param_server: support for custom params

---

pb_plugins/protoc_gen_mavsdk/autogen.py
pb_plugins/protoc_gen_mavsdk/autogen_file.py
pb_plugins/protoc_gen_mavsdk/methods.py
pb_plugins/protoc_gen_mavsdk/utils.py
protos/camera_server/camera_server.proto
protos/param/param.proto
protos/param_server/param_server.proto

This is the proto work that goes with https://github.com/mavlink/MAVSDK/pull/1733.
@JonasVautherin it would be awesome to get your review on the `protoc-gen-mavsdk` additions.

Server component protoc-gen-mavsdk additions and camera server

---

pb_plugins/requirements.txt

We can't update yet because it conflicts with grpcio-tools.

Fix protobuf version for now

---

protos/follow_me/follow_me.proto

Due to the ongoing refactor of Follow Me in PX4, the enumerations as well as parameters have been changed. Therefore the proto file needs to be updated as well.
Upstream PR : https://github.com/PX4/PX4-Autopilot/pull/19260

Update follow_me.proto to match PX4 Upstream

---

protos/gimbal/gimbal.proto
protos/mission/mission.proto
protos/mission_raw/mission_raw.proto

We should rely less on the log messages which only show up as side effects.

More mission and mission_raw results

---

protos/mission_raw/mission_raw.proto

Taken from here: https://github.com/mavlink/MAVSDK-Proto/compare/pr-add-rally-geofence...volansi:pr-add-rally-geofence

mission_raw: Add support for geofence and rally points

---

protos/info/info.proto

Trying to close [#1910](https://github.com/mavlink/MAVSDK/issues/1910)

Added Software version type to Info proto

---

protos/info/info.proto

info: remove trailing whitespace

---

protos/telemetry/telemetry.proto

Closes [#1928](https://github.com/mavlink/MAVSDK/issues/1928)

Add bottom_clearance to altitude in telemetry

---

protos/geofence/geofence.proto

It would be really nice to have support for circular geofences in Geofence plugin.

geofence: Add support for circular geofences

---

protos/log_files/log_files.proto

fixes https://github.com/mavlink/MAVSDK-Python/issues/534

log_files: remove synchronous DownloadLogFile

---

protos/camera_server/camera_server.proto

This implements continuous and range zooming.

camera_server: implement zoom

---

protos/action/action.proto

It's just handy for bench things.

action: add force-arming

---

protos/info/info.proto

This allows to get the flight information update once per second.

info: add subscription for flight information

---

protos/events/events.proto

Proto file for https://github.com/mavlink/MAVSDK/pull/2338

Events plugin

---

.github/workflows/main.yml

CI: fix deploy

---

protos/mission_raw/mission_raw.proto
protos/mocap/mocap.proto
protos/offboard/offboard.proto
protos/shell/shell.proto

The double asteriks become a list in documentation and cause trouble there.

Fix comment syntax

---

protos/telemetry/telemetry.proto

Add Mavlink WindCov to Proto REF -> [Mavlink WIND_COV Ref](https://mavlink.io/en/messages/common.html#WIND_COV)
I will update WindCov_impl in MAVSDK-CPP after this PR Done.

Add Wind proto

---

protos/telemetry/telemetry.proto

Add component of battery status
1. Battery Remaining Time
2. Battery Function

Update battery status

---

protos/mission_raw/mission_raw.proto

We already have this for mission, so it makes sense to mirror it for mission_raw.

mission_raw: add check if mission is finished

---

pb_plugins/requirements.txt

Related to https://github.com/mavlink/MAVSDK-Python/issues/763.

pb_plugins: bump protobuf
